Repository jwstegemann/fritz2, pull requests merged in 2021-04, with the labels that each got.

#327 Add macOS-specific .DS_Store files to gitignore
  .gitignore
Labels: enhancement

#317 Using websafe fonts in default theme
  styling/src/jsMain/kotlin/dev.fritz2.styling/theme/default.kt
Labels: enhancement

#335 Added missing resizeBehavior option `both`
  components/src/jsMain/kotlin/dev/fritz2/components/textarea.kt
  styling/src/jsMain/kotlin/dev.fritz2.styling/theme/default.kt
  styling/src/jsMain/kotlin/dev.fritz2.styling/theme/definitions.kt
Labels: api improvement, bug, enhancement

#331 Using DSLMarkers for Components
  components/src/jsMain/kotlin/dev/fritz2/components/alert.kt
  components/src/jsMain/kotlin/dev/fritz2/components/appFrame.kt
  components/src/jsMain/kotlin/dev/fritz2/components/button.kt
  components/src/jsMain/kotlin/dev/fritz2/components/checkbox.kt
  components/src/jsMain/kotlin/dev/fritz2/components/checkboxGroup.kt
  components/src/jsMain/kotlin/dev/fritz2/components/components.kt
  components/src/jsMain/kotlin/dev/fritz2/components/file.kt
  components/src/jsMain/kotlin/dev/fritz2/components/formcontrol.kt
  components/src/jsMain/kotlin/dev/fritz2/components/icons.kt
  components/src/jsMain/kotlin/dev/fritz2/components/input.kt
  components/src/jsMain/kotlin/dev/fritz2/components/managed.kt
  components/src/jsMain/kotlin/dev/fritz2/components/modal.kt
  components/src/jsMain/kotlin/dev/fritz2/components/nav.kt
  components/src/jsMain/kotlin/dev/fritz2/components/navbar.kt
  components/src/jsMain/kotlin/dev/fritz2/components/popover.kt
  components/src/jsMain/kotlin/dev/fritz2/components/radio.kt
  components/src/jsMain/kotlin/dev/fritz2/components/radioGroup.kt
  components/src/jsMain/kotlin/dev/fritz2/components/select.kt
  components/src/jsMain/kotlin/dev/fritz2/components/spinner.kt
  components/src/jsMain/kotlin/dev/fritz2/components/stack.kt
  components/src/jsMain/kotlin/dev/fritz2/components/switch.kt
  components/src/jsMain/kotlin/dev/fritz2/components/textarea.kt
  components/src/jsMain/kotlin/dev/fritz2/components/toast.kt
  components/src/jsMain/resources/reset.css
  core/src/jsMain/kotlin/dev/fritz2/binding/job.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/events.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/tag.kt
Labels: api improvement, enhancement

#336 Fix horizontal and vertical convenience functions of BordersContext DSL
  styling/src/jsMain/kotlin/dev.fritz2.styling/params/border.kt
Labels: api breaking, api improvement, bug

#334 Rework of API for Keys from KeyboardEvents
  components/src/jsMain/kotlin/dev/fritz2/components/popover.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/html/events.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/listener.kt
  core/src/jsTest/kotlin/dev/fritz2/dom/listener.kt
Labels: api breaking, api improvement

#338 Fixed problem with nested renders which contains conditions
  core/src/jsMain/kotlin/dev/fritz2/binding/store.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/tag.kt
  core/src/jsTest/kotlin/dev/fritz2/dom/tag.kt
Labels: bug

#340 Moved mono icons to an extra package next to the License.md
  styling/src/jsMain/kotlin/dev.fritz2.styling/theme/default.kt
  styling/src/jsMain/kotlin/dev.fritz2.styling/theme/icons/MonoIcons.kt
Labels: enhancement

#345 Make `staticStyle` internal
  components/src/jsMain/kotlin/dev/fritz2/components/appFrame.kt
  components/src/jsMain/kotlin/dev/fritz2/components/nav.kt
  components/src/jsMain/kotlin/dev/fritz2/components/radio.kt
  styling/src/jsMain/kotlin/dev.fritz2.styling/style.kt
Labels: enhancement

#355 Extends of ColorScheme approach
  components/src/jsMain/kotlin/dev/fritz2/components/alert.kt
  components/src/jsMain/kotlin/dev/fritz2/components/button.kt
  components/src/jsMain/kotlin/dev/fritz2/components/navbar.kt
  components/src/jsMain/kotlin/dev/fritz2/components/textarea.kt
  components/src/jsMain/kotlin/dev/fritz2/components/toast.kt
  styling/src/jsMain/kotlin/dev.fritz2.styling/theme/default.kt
  styling/src/jsMain/kotlin/dev.fritz2.styling/theme/definitions.kt
  styling/src/jsMain/kotlin/dev.fritz2.styling/utils.kt
Labels: api breaking, api improvement, enhancement

#356 Improve API of AlertComponent and use new color scheme
  components/src/jsMain/kotlin/dev/fritz2/components/alert.kt
  styling/src/jsMain/kotlin/dev.fritz2.styling/theme/default.kt
  styling/src/jsMain/kotlin/dev.fritz2.styling/theme/definitions.kt
Labels: api breaking, api improvement, enhancement

#350 Add DataTable component
  components/src/jsMain/kotlin/dev/fritz2/components/datatable.kt
  components/src/jsMain/kotlin/dev/fritz2/components/datatable/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/datatable/context.kt
  components/src/jsMain/kotlin/dev/fritz2/components/datatable/foundation.kt
  components/src/jsMain/kotlin/dev/fritz2/components/datatable/selection.kt
  components/src/jsMain/kotlin/dev/fritz2/components/datatable/sorting.kt
  styling/src/jsMain/kotlin/dev.fritz2.styling/theme/default.kt
  styling/src/jsMain/kotlin/dev.fritz2.styling/theme/definitions.kt
  styling/src/jsMain/kotlin/dev.fritz2.styling/theme/theme.kt
Labels: enhancement

#337 Extend styling API
  components/src/jsMain/kotlin/dev/fritz2/components/alert.kt
  components/src/jsMain/kotlin/dev/fritz2/components/appFrame.kt
  components/src/jsMain/kotlin/dev/fritz2/components/box.kt
  components/src/jsMain/kotlin/dev/fritz2/components/button.kt
  components/src/jsMain/kotlin/dev/fritz2/components/checkbox.kt
  components/src/jsMain/kotlin/dev/fritz2/components/checkboxGroup.kt
  components/src/jsMain/kotlin/dev/fritz2/components/components.kt
  components/src/jsMain/kotlin/dev/fritz2/components/datatable.kt
  components/src/jsMain/kotlin/dev/fritz2/components/datatable/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/datatable/context.kt
  components/src/jsMain/kotlin/dev/fritz2/components/file.kt
  components/src/jsMain/kotlin/dev/fritz2/components/formcontrol.kt
  components/src/jsMain/kotlin/dev/fritz2/components/icons.kt
  components/src/jsMain/kotlin/dev/fritz2/components/input.kt
  components/src/jsMain/kotlin/dev/fritz2/components/nav.kt
  components/src/jsMain/kotlin/dev/fritz2/components/navbar.kt
  components/src/jsMain/kotlin/dev/fritz2/components/popover.kt
  components/src/jsMain/kotlin/dev/fritz2/components/radio.kt
  components/src/jsMain/kotlin/dev/fritz2/components/radioGroup.kt
  components/src/jsMain/kotlin/dev/fritz2/components/select.kt
  components/src/jsMain/kotlin/dev/fritz2/components/spinner.kt
  components/src/jsMain/kotlin/dev/fritz2/components/switch.kt
  components/src/jsMain/kotlin/dev/fritz2/components/textarea.kt
  components/src/jsMain/kotlin/dev/fritz2/components/toast.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/html/elements.kt
  styling/src/jsMain/kotlin/dev.fritz2.styling/utils.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/hash/murmurhash.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/params/alignment.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/params/background.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/params/border.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/params/color.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/params/flexbox.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/params/gridLayout.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/params/layout.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/params/params.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/params/position.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/params/pseudos.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/params/shadow.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/params/space.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/params/styledElements.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/params/typography.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/style.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/styling.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/stylis/stylis.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/definitions.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/icons/LICENSE.md
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/icons/MonoIcons.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/theme.kt
Labels: api improvement, enhancement

#358 Polish DataTable
  components/src/jsMain/kotlin/dev/fritz2/components/datatable/context.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
Labels: api improvement, enhancement

#357 Move background & font colors to `Colors` interface
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/definitions.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/theme.kt
Labels: api breaking, api improvement

#359 Rework new `Svg` tag in core
  components/src/jsMain/kotlin/dev/fritz2/components/icons.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/html/elements.kt
Labels: api improvement

#370 remove misleading `Inter` font
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
Labels: enhancement
