Repository jwstegemann/fritz2, pull requests merged in 2021-09, with the labels that each got.

#519 Add often used attributes for svg and path element
  core/src/jsMain/kotlin/dev/fritz2/dom/html/elements.kt
Labels: enhancement

#521 Handle possible ClassCastException
  core/src/jsMain/kotlin/dev/fritz2/dom/window.kt
Labels: bug

#522 Expose open/close handlers or an external store for submenu component
  components/src/jsMain/kotlin/dev/fritz2/components/menu/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/menu/context.kt
Labels: api improvement

#503 Fix problem with missing ids on components with `for` attribute (radio, checkbox, switch)
  components/src/commonMain/kotlin/dev/fritz2/components/validation/validation.kt
  components/src/jsMain/kotlin/dev/fritz2/components/checkbox.kt
  components/src/jsMain/kotlin/dev/fritz2/components/checkboxGroup.kt
  components/src/jsMain/kotlin/dev/fritz2/components/checkboxes/componentGroup.kt
  components/src/jsMain/kotlin/dev/fritz2/components/checkboxes/componentSingle.kt
  components/src/jsMain/kotlin/dev/fritz2/components/datatable/context.kt
  components/src/jsMain/kotlin/dev/fritz2/components/datatable/selection.kt
  components/src/jsMain/kotlin/dev/fritz2/components/forms/control/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/forms/control/renderer.kt
  components/src/jsMain/kotlin/dev/fritz2/components/foundations/properties.kt
  components/src/jsMain/kotlin/dev/fritz2/components/inputField.kt
  components/src/jsMain/kotlin/dev/fritz2/components/inputField/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/radio.kt
  components/src/jsMain/kotlin/dev/fritz2/components/radioGroup.kt
  components/src/jsMain/kotlin/dev/fritz2/components/radios/componentGroup.kt
  components/src/jsMain/kotlin/dev/fritz2/components/radios/componentSingle.kt
  components/src/jsMain/kotlin/dev/fritz2/components/select.kt
  components/src/jsMain/kotlin/dev/fritz2/components/selectField/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/slider.kt
  components/src/jsMain/kotlin/dev/fritz2/components/slider/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/switch.kt
  components/src/jsMain/kotlin/dev/fritz2/components/switch/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/textarea.kt
  components/src/jsMain/kotlin/dev/fritz2/components/textarea/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/toast/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/typeAhead.kt
  components/src/jsMain/kotlin/dev/fritz2/components/typeAhead/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/validation/validation.kt
  core/src/commonMain/kotlin/dev/fritz2/identification/id.kt
  core/src/commonMain/kotlin/dev/fritz2/identification/inspector.kt
  core/src/commonMain/kotlin/dev/fritz2/validation/validation.kt
  core/src/commonTest/kotlin/dev/fritz2/identification/inspector.kt
  core/src/commonTest/kotlin/dev/fritz2/validation/validation.kt
  core/src/jsMain/kotlin/dev/fritz2/binding/store.kt
  core/src/jsMain/kotlin/dev/fritz2/binding/substores.kt
  core/src/jsMain/kotlin/dev/fritz2/identification/id.kt
  core/src/jsMain/kotlin/dev/fritz2/validation/validation.kt
  core/src/jsTest/kotlin/dev/fritz2/binding/events.kt
  core/src/jsTest/kotlin/dev/fritz2/binding/mount.kt
  core/src/jsTest/kotlin/dev/fritz2/binding/seq.kt
  core/src/jsTest/kotlin/dev/fritz2/binding/store.kt
  core/src/jsTest/kotlin/dev/fritz2/binding/substores.kt
  core/src/jsTest/kotlin/dev/fritz2/dom/attributes.kt
  core/src/jsTest/kotlin/dev/fritz2/dom/comment.kt
  core/src/jsTest/kotlin/dev/fritz2/dom/html/mount.kt
  core/src/jsTest/kotlin/dev/fritz2/dom/html/render.kt
  core/src/jsTest/kotlin/dev/fritz2/dom/html/scope.kt
  core/src/jsTest/kotlin/dev/fritz2/dom/listener.kt
  core/src/jsTest/kotlin/dev/fritz2/dom/tag.kt
  core/src/jsTest/kotlin/dev/fritz2/dom/text.kt
  core/src/jsTest/kotlin/dev/fritz2/history/history.kt
  core/src/jsTest/kotlin/dev/fritz2/remote/websocket.kt
  core/src/jsTest/kotlin/dev/fritz2/repositories/localstorage/localStorage.kt
  core/src/jsTest/kotlin/dev/fritz2/repositories/rest/rest.kt
  core/src/jsTest/kotlin/dev/fritz2/routing/routing.kt
  core/src/jsTest/kotlin/dev/fritz2/tracking/tracking.kt
  core/src/jsTest/kotlin/dev/fritz2/validation/validation.kt
  core/src/jvmMain/kotlin/dev/fritz2/identification/id.kt
  core/src/jvmMain/kotlin/dev/fritz2/validation/validation.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
Labels: bug

#523 Fixed not working `disabled` property in `formControl` component
  components/src/jsMain/kotlin/dev/fritz2/components/forms/control/component.kt
Labels: bug

#524 fix baseClass at Svg and Path
  core/src/jsMain/kotlin/dev/fritz2/dom/html/elements.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/listener.kt
Labels: bug

#525 Improve null value handling for attribute setting
  core/src/jsMain/kotlin/dev/fritz2/dom/tag.kt
  core/src/jsTest/kotlin/dev/fritz2/dom/attributes.kt
Labels: api improvement

#528 chausknecht/dynamicSubmenuIcons
  components/src/jsMain/kotlin/dev/fritz2/components/menu/component.kt
Labels: enhancement, component/styling
