Repository jwstegemann/fritz2, pull requests merged in 2021-06, with the labels that each got.

#369 Added convenience methods `inspectEach()` for `Inspector`
  core/src/commonMain/kotlin/dev/fritz2/identification/inspector.kt
  core/src/commonTest/kotlin/dev/fritz2/identification/inspector.kt
Labels: api improvement, enhancement

#390 Fix css error in `appFrame` component
  components/src/jsMain/kotlin/dev/fritz2/components/appFrame.kt
Labels: bug

#361 Improve `ComponentValidationMessage.asAlert()`
  components/src/jsMain/kotlin/dev/fritz2/components/alert.kt
  components/src/jsMain/kotlin/dev/fritz2/components/formcontrol.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
Labels: api improvement

#387 Add Slider Component
  components/src/jsMain/kotlin/dev/fritz2/components/formcontrol.kt
  components/src/jsMain/kotlin/dev/fritz2/components/slider.kt
  components/src/jsMain/kotlin/dev/fritz2/components/slider/component.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/definitions.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/theme.kt
Labels: enhancement

#420 Using `ComponentProperty` for setting an `IconDefinition` for a button
  components/src/jsMain/kotlin/dev/fritz2/components/alert.kt
  components/src/jsMain/kotlin/dev/fritz2/components/appFrame.kt
  components/src/jsMain/kotlin/dev/fritz2/components/components.kt
  components/src/jsMain/kotlin/dev/fritz2/components/dropdown.kt
  components/src/jsMain/kotlin/dev/fritz2/components/file.kt
  components/src/jsMain/kotlin/dev/fritz2/components/pushButton.kt
Labels: api breaking, api improvement

#422 Fixed self type loss after using global functions on `Listener` like `preventDefault` etc.
  core/src/jsMain/kotlin/dev/fritz2/dom/listener.kt
  core/src/jsTest/kotlin/dev/fritz2/dom/listener.kt
Labels: bug

#423 Removed duplicated html elements which causing errors
  core/src/jsMain/kotlin/dev/fritz2/dom/html/elements.kt
Labels: bug

#415 Use constant values for z-indices in components
  components/src/jsMain/kotlin/dev/fritz2/components/appFrame.kt
  components/src/jsMain/kotlin/dev/fritz2/components/datatable/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/managed.kt
  components/src/jsMain/kotlin/dev/fritz2/components/modal.kt
  components/src/jsMain/kotlin/dev/fritz2/components/navbar.kt
  components/src/jsMain/kotlin/dev/fritz2/components/toast.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/definitions.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/theme.kt
Labels: api breaking, bug

#417 Harmonize orientation settings
  components/src/jsMain/kotlin/dev/fritz2/components/checkboxGroup.kt
  components/src/jsMain/kotlin/dev/fritz2/components/components.kt
  components/src/jsMain/kotlin/dev/fritz2/components/radioGroup.kt
  components/src/jsMain/kotlin/dev/fritz2/components/slider/component.kt
Labels: api improvement

#424 Improve Menu- and DropdownComponent
  components/src/jsMain/kotlin/dev/fritz2/components/dropdown.kt
  components/src/jsMain/kotlin/dev/fritz2/components/menu.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/definitions.kt
Labels: api improvement, enhancement

#409 Upgrade to Kotlin 1.5
  README.md
  build.gradle.kts
  components/build.gradle.kts
  components/src/jsMain/kotlin/dev/fritz2/components/file.kt
  core/build.gradle.kts
  core/src/jsMain/kotlin/dev/fritz2/dom/events.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/tag.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/window.kt
  core/src/jsMain/kotlin/dev/fritz2/remote/websocket.kt
  core/src/jsMain/kotlin/dev/fritz2/webcomponents/webcomponents.kt
  core/src/jsTest/kotlin/dev/fritz2/utils/myer.kt
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  lenses-annotation-processor/build.gradle.kts
  lenses-annotation-processor/src/jvmMain/kotlin/dev/fritz2/lenses/LensesAnnotationProcessor.kt
  lenses-annotation-processor/src/jvmTest/kotlin/dev/fritz2/lenses/LensesAnnotationProcessorTests.kt
  settings.gradle.kts
  styling/build.gradle.kts
  styling/src/jsMain/kotlin/dev/fritz2/styling/style.kt
  test-server/build.gradle.kts
Labels: api breaking, enhancement

#427 Update murmurhash version to 2.0.0
  build.gradle.kts
Labels: enhancement

#430 Make track safe for unsafe operations
  core/src/jsMain/kotlin/dev/fritz2/tracking/tracking.kt
  core/src/jsTest/kotlin/dev/fritz2/tracking/tracking.kt
Labels: bug

#443 Use any element/component as a label in radio- and checkbox-groups
  components/src/jsMain/kotlin/dev/fritz2/components/checkboxGroup.kt
  components/src/jsMain/kotlin/dev/fritz2/components/radioGroup.kt
Labels: api improvement, enhancement

#442 Rework modal
  components/src/jsMain/kotlin/dev/fritz2/components/components.kt
  components/src/jsMain/kotlin/dev/fritz2/components/modal.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/definitions.kt
Labels: api improvement, bug, enhancement

#434 Use explicit type specification for `Icons` in `DefaultTheme`
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
Labels: api improvement, bug

#435 Added new `reset()` function to `Validator`
  core/src/jsMain/kotlin/dev/fritz2/validation/validation.kt
  core/src/jvmMain/kotlin/dev/fritz2/validation/validation.kt
Labels: api improvement

#436 Rework `popover` component
  components/src/jsMain/kotlin/dev/fritz2/components/dropdown.kt
  components/src/jsMain/kotlin/dev/fritz2/components/popover.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/listener.kt
Labels: api improvement, enhancement

#452 Add formGroup component
  components/src/jsMain/kotlin/dev/fritz2/components/formGroup.kt
  components/src/jsMain/kotlin/dev/fritz2/components/formcontrol.kt
  components/src/jsMain/kotlin/dev/fritz2/components/forms/common.kt
  components/src/jsMain/kotlin/dev/fritz2/components/forms/control/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/forms/control/renderer.kt
  components/src/jsMain/kotlin/dev/fritz2/components/forms/group/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/textarea.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/style.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/definitions.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/theme.kt
Labels: enhancement

#458 added missing package line in `select.kt` and `nav.kt`
  components/src/jsMain/kotlin/dev/fritz2/components/forms/control/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/nav.kt
  components/src/jsMain/kotlin/dev/fritz2/components/select.kt
Labels: bug
