Repository jwstegemann/fritz2, pull requests merged in 2021-11, with the labels that each got.

#541 Upgrade to gradle 7.2
  build.gradle.kts
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  lenses-annotation-processor/build.gradle.kts
  test-server/build.gradle.kts
Labels: enhancement

#543 `Router` is now a `Store`
  core/src/jsMain/kotlin/dev/fritz2/binding/store.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/html/job.kt
  core/src/jsMain/kotlin/dev/fritz2/routing/routing.kt
  core/src/jsTest/kotlin/dev/fritz2/routing/routing.kt
Labels: api improvement, api breaking

#546 Use a SharedFlow for Web Component attribute changes
  core/src/jsMain/kotlin/dev/fritz2/webcomponents/webcomponents.kt
  core/src/jsTest/kotlin/dev/fritz2/webcomponents/webcomponent.kt
Labels: bug
