Repository jwstegemann/fritz2, pull requests merged in 2021-12, with the labels that each got.

#557 Fix for issue #550: Removed touchends-event scrolling from appFrame component
  components/src/jsMain/kotlin/dev/fritz2/components/appFrame/component.kt
Labels: bug, component/styling

#556 Improve Key API and keys event handling
  components/src/jsMain/kotlin/dev/fritz2/components/popover.kt
  components/src/jsMain/kotlin/dev/fritz2/components/slider/component.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/html/events.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/listener.kt
  core/src/jsTest/kotlin/dev/fritz2/dom/html/events.kt
  core/src/jsTest/kotlin/dev/fritz2/dom/listener.kt
Labels: enhancement, api improvement

#558 Added `Middleware` support to html API + pre-build stateless `Authentication` middleware
  core/src/jsMain/kotlin/dev/fritz2/remote/auth.kt
  core/src/jsMain/kotlin/dev/fritz2/remote/http.kt
  core/src/jsMain/kotlin/dev/fritz2/remote/middleware.kt
  core/src/jsMain/kotlin/dev/fritz2/repositories/rest/rest.kt
  core/src/jsTest/kotlin/dev/fritz2/dom/tag.kt
  core/src/jsTest/kotlin/dev/fritz2/remote/auth.kt
  core/src/jsTest/kotlin/dev/fritz2/remote/http.kt
  core/src/jsTest/kotlin/dev/fritz2/remote/middleware.kt
  core/src/jsTest/kotlin/dev/fritz2/test/utils.kt
  test-server/src/main/kotlin/dev/fritz2/Server.kt
Labels: enhancement, api breaking
