Repository jwstegemann/fritz2, pull requests merged in 2021-07, with the labels that each got.

#471 Fix close-button margin in `ToastComponent`
  components/src/jsMain/kotlin/dev/fritz2/components/toast.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/definitions.kt
Labels: bug

#462 Rename alert variant `discreet` to `ghost`
  components/src/jsMain/kotlin/dev/fritz2/components/alert.kt
  components/src/jsMain/kotlin/dev/fritz2/components/forms/control/component.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/definitions.kt
Labels: api breaking, api improvement

#487 Rework `ToastComponent`
  components/src/jsMain/kotlin/dev/fritz2/components/toast.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/definitions.kt
Labels: api breaking

#488 Restructure components and API documentation
  components/src/jsMain/kotlin/dev/fritz2/components/alert.kt
  components/src/jsMain/kotlin/dev/fritz2/components/alert/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/appFrame.kt
  components/src/jsMain/kotlin/dev/fritz2/components/buttons.kt
  components/src/jsMain/kotlin/dev/fritz2/components/buttons/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/checkbox.kt
  components/src/jsMain/kotlin/dev/fritz2/components/checkboxGroup.kt
  components/src/jsMain/kotlin/dev/fritz2/components/checkboxes/componentGroup.kt
  components/src/jsMain/kotlin/dev/fritz2/components/checkboxes/componentSingle.kt
  components/src/jsMain/kotlin/dev/fritz2/components/datatable/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/datatable/context.kt
  components/src/jsMain/kotlin/dev/fritz2/components/dropdown.kt
  components/src/jsMain/kotlin/dev/fritz2/components/file.kt
  components/src/jsMain/kotlin/dev/fritz2/components/file/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/forms/control/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/forms/group/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/foundations/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/foundations/managed.kt
  components/src/jsMain/kotlin/dev/fritz2/components/foundations/mixins.kt
  components/src/jsMain/kotlin/dev/fritz2/components/foundations/properties.kt
  components/src/jsMain/kotlin/dev/fritz2/components/foundations/stores.kt
  components/src/jsMain/kotlin/dev/fritz2/components/icon/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/icons.kt
  components/src/jsMain/kotlin/dev/fritz2/components/inputField.kt
  components/src/jsMain/kotlin/dev/fritz2/components/inputField/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/linkButton.kt
  components/src/jsMain/kotlin/dev/fritz2/components/menu.kt
  components/src/jsMain/kotlin/dev/fritz2/components/modal.kt
  components/src/jsMain/kotlin/dev/fritz2/components/modal/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/nav.kt
  components/src/jsMain/kotlin/dev/fritz2/components/navbar.kt
  components/src/jsMain/kotlin/dev/fritz2/components/popover.kt
  components/src/jsMain/kotlin/dev/fritz2/components/radio.kt
  components/src/jsMain/kotlin/dev/fritz2/components/radioGroup.kt
  components/src/jsMain/kotlin/dev/fritz2/components/radios/componentGroup.kt
  components/src/jsMain/kotlin/dev/fritz2/components/radios/componentSingle.kt
  components/src/jsMain/kotlin/dev/fritz2/components/select.kt
  components/src/jsMain/kotlin/dev/fritz2/components/selectField/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/slider/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/spinner.kt
  components/src/jsMain/kotlin/dev/fritz2/components/spinner/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/stacks.kt
  components/src/jsMain/kotlin/dev/fritz2/components/stacks/components.kt
  components/src/jsMain/kotlin/dev/fritz2/components/switch.kt
  components/src/jsMain/kotlin/dev/fritz2/components/switch/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/textarea.kt
  components/src/jsMain/kotlin/dev/fritz2/components/textarea/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/toast.kt
  components/src/jsMain/kotlin/dev/fritz2/components/toast/component.kt
Labels: api breaking, api improvement, documentation

#490 Move Modal's close handler into content property
  components/src/jsMain/kotlin/dev/fritz2/components/modal.kt
  components/src/jsMain/kotlin/dev/fritz2/components/modal/component.kt
Labels: api breaking, api improvement

#492 Remove deprecated `direction`-api from `RadioGroupComponent` and `CheckboxGroupComponent`
  components/src/jsMain/kotlin/dev/fritz2/components/checkboxes/componentGroup.kt
  components/src/jsMain/kotlin/dev/fritz2/components/radios/componentGroup.kt
Labels: api breaking

#494 Allow `sub()` on all `Store´s
  components/src/jsMain/kotlin/dev/fritz2/components/datatable/context.kt
  components/src/jsMain/kotlin/dev/fritz2/components/datatable/foundation.kt
  components/src/jsMain/kotlin/dev/fritz2/components/datatable/selection.kt
  components/src/jsMain/kotlin/dev/fritz2/components/validation/validation.kt
  core/src/jsMain/kotlin/dev/fritz2/binding/store.kt
  core/src/jsMain/kotlin/dev/fritz2/binding/substores.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/tag.kt
  core/src/jsTest/kotlin/dev/fritz2/binding/substores.kt
Labels: api breaking, api improvement
