Repository jwstegemann/fritz2, pull requests merged in 2021-08, with the labels that each got.

#470 Add TypeAhead Component
  components/src/jsMain/kotlin/dev/fritz2/components/forms/control/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/foundations/mixins.kt
  components/src/jsMain/kotlin/dev/fritz2/components/inputField/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/typeAhead.kt
  components/src/jsMain/kotlin/dev/fritz2/components/typeAhead/component.kt
  core/src/jsMain/kotlin/dev/fritz2/binding/store.kt
Labels: enhancement

#502 fix type of InputEvent
  core/src/jsMain/kotlin/dev/fritz2/dom/events.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/html/events.kt
Labels: bug

#481 Add possibility to pass arbitrary payload data in fritz2's DSL
  components/src/jsMain/kotlin/dev/fritz2/components/appFrame.kt
  components/src/jsMain/kotlin/dev/fritz2/components/appFrame/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/buttons.kt
  components/src/jsMain/kotlin/dev/fritz2/components/foundations/managed.kt
  components/src/jsMain/kotlin/dev/fritz2/components/menu.kt
  components/src/jsMain/kotlin/dev/fritz2/components/menu/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/menu/context.kt
  components/src/jsMain/kotlin/dev/fritz2/components/menu/entries.kt
  components/src/jsMain/kotlin/dev/fritz2/components/modal/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/nav.kt
  components/src/jsMain/kotlin/dev/fritz2/components/toast/component.kt
  core/src/jsMain/kotlin/dev/fritz2/binding/store.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/events.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/html/elements.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/html/job.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/html/render.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/html/scope.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/tag.kt
  core/src/jsMain/kotlin/dev/fritz2/webcomponents/webcomponents.kt
  core/src/jsTest/kotlin/dev/fritz2/dom/html/scope.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/styling.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/definitions.kt
Labels: enhancement

#486 Use colors in `appFrame` and added `submenu` in `menu` component
  components/src/jsMain/kotlin/dev/fritz2/components/appFrame.kt
  components/src/jsMain/kotlin/dev/fritz2/components/appFrame/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/appFrame/scope.kt
  components/src/jsMain/kotlin/dev/fritz2/components/appFrame/service.kt
  components/src/jsMain/kotlin/dev/fritz2/components/box.kt
  components/src/jsMain/kotlin/dev/fritz2/components/checkboxes/componentSingle.kt
  components/src/jsMain/kotlin/dev/fritz2/components/menu.kt
  components/src/jsMain/kotlin/dev/fritz2/components/menu/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/menu/context.kt
  components/src/jsMain/kotlin/dev/fritz2/components/menu/entries.kt
  components/src/jsMain/kotlin/dev/fritz2/components/radios/componentSingle.kt
  components/src/jsMain/kotlin/dev/fritz2/components/switch/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/toast/component.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/definitions.kt
Labels: api improvement

#493 Add `PopupComponent`
  components/src/jsMain/kotlin/dev/fritz2/components/popup.kt
  components/src/jsMain/kotlin/dev/fritz2/components/popup/Placement.kt
  components/src/jsMain/kotlin/dev/fritz2/components/popup/Positioning.kt
  components/src/jsMain/kotlin/dev/fritz2/components/popup/TriggerInformation.kt
  components/src/jsMain/kotlin/dev/fritz2/components/popup/component.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/definitions.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/theme.kt
Labels: enhancement

#510 Optimize DataTable's reactive rendering
  components/src/jsMain/kotlin/dev/fritz2/components/datatable/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/datatable/foundation.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
Labels: enhancement

#505 Add `TooltipComponent`
  components/src/jsMain/kotlin/dev/fritz2/components/popup/component.kt
  components/src/jsMain/kotlin/dev/fritz2/components/tooltip.kt
  components/src/jsMain/kotlin/dev/fritz2/components/tooltip/component.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/default.kt
  styling/src/jsMain/kotlin/dev/fritz2/styling/theme/definitions.kt
Labels: enhancement

#515 Handle possible CastException
  core/src/jsMain/kotlin/dev/fritz2/dom/events.kt
Labels: bug
