Repository jwstegemann/fritz2, pull requests merged in 2021-02, with the labels that each got.

#268 Rework element property prioritization
  components/src/jsMain/kotlin/dev/fritz2/components/button.kt
  components/src/jsMain/kotlin/dev/fritz2/components/checkbox.kt
  components/src/jsMain/kotlin/dev/fritz2/components/input.kt
  components/src/jsMain/kotlin/dev/fritz2/components/popover.kt
  components/src/jsMain/kotlin/dev/fritz2/components/radio.kt
  components/src/jsMain/kotlin/dev/fritz2/components/switch.kt
  components/src/jsMain/kotlin/dev/fritz2/components/textarea.kt
Labels: api improvement

#266 Add missing event contexts
  components/src/jsMain/kotlin/dev/fritz2/components/icons.kt
  components/src/jsMain/kotlin/dev/fritz2/components/spinner.kt
  components/src/jsMain/kotlin/dev/fritz2/components/stack.kt
Labels: api improvement

#262 added app-component (pwa) and nav-components
  components/src/jsMain/kotlin/dev/fritz2/components/appFrame.kt
  components/src/jsMain/kotlin/dev/fritz2/components/nav.kt
  styling/src/jsMain/kotlin/dev.fritz2.styling/theme/default.kt
  styling/src/jsMain/kotlin/dev.fritz2.styling/theme/definitions.kt
  styling/src/jsMain/kotlin/dev.fritz2.styling/theme/theme.kt
Labels: enhancement

#273 Fix AppFrame height on Firefox
  components/src/jsMain/kotlin/dev/fritz2/components/appFrame.kt
Labels: bug

#269 Refactor internal component structure
  components/src/jsMain/kotlin/dev/fritz2/components/alert.kt
  components/src/jsMain/kotlin/dev/fritz2/components/appFrame.kt
  components/src/jsMain/kotlin/dev/fritz2/components/button.kt
  components/src/jsMain/kotlin/dev/fritz2/components/checkbox.kt
  components/src/jsMain/kotlin/dev/fritz2/components/checkboxGroup.kt
  components/src/jsMain/kotlin/dev/fritz2/components/components.kt
  components/src/jsMain/kotlin/dev/fritz2/components/file.kt
  components/src/jsMain/kotlin/dev/fritz2/components/formcontrol.kt
  components/src/jsMain/kotlin/dev/fritz2/components/icons.kt
  components/src/jsMain/kotlin/dev/fritz2/components/input.kt
  components/src/jsMain/kotlin/dev/fritz2/components/modal.kt
  components/src/jsMain/kotlin/dev/fritz2/components/nav.kt
  components/src/jsMain/kotlin/dev/fritz2/components/popover.kt
  components/src/jsMain/kotlin/dev/fritz2/components/radio.kt
  components/src/jsMain/kotlin/dev/fritz2/components/radioGroup.kt
  components/src/jsMain/kotlin/dev/fritz2/components/select.kt
  components/src/jsMain/kotlin/dev/fritz2/components/spinner.kt
  components/src/jsMain/kotlin/dev/fritz2/components/stack.kt
  components/src/jsMain/kotlin/dev/fritz2/components/switch.kt
  components/src/jsMain/kotlin/dev/fritz2/components/textarea.kt
  components/src/jsMain/kotlin/dev/fritz2/components/toast.kt
Labels: api improvement, documentation

#275 Improve CloseButton API
  components/src/jsMain/kotlin/dev/fritz2/components/components.kt
  components/src/jsMain/kotlin/dev/fritz2/components/modal.kt
  components/src/jsMain/kotlin/dev/fritz2/components/popover.kt
  components/src/jsMain/kotlin/dev/fritz2/components/toast.kt
Labels: api improvement
