Repository jwstegemann/fritz2, pull requests merged in 2022-01, with the labels that each got.

#560 Removed deprecated `uniqueId()` function -> use `Id.next()` instead
  core/src/commonMain/kotlin/dev/fritz2/identification/id.kt
  core/src/jsMain/kotlin/dev/fritz2/identification/id.kt
  core/src/jvmMain/kotlin/dev/fritz2/identification/id.kt
Labels: api breaking

#559 Apply KSP as substitute for KAPT for automatic lenses generation
  build.gradle.kts
  components/src/jsMain/kotlin/dev/fritz2/components/file.kt
  components/src/jsMain/kotlin/dev/fritz2/components/file/component.kt
  kotlin-js-store/yarn.lock
  lenses-annotation-processor/build.gradle.kts
  lenses-annotation-processor/src/jvmMain/kotlin/dev/fritz2/lenses/LensesAnnotationProcessor.kt
  lenses-annotation-processor/src/jvmMain/kotlin/dev/fritz2/lenses/LensesProcessor.kt
  lenses-annotation-processor/src/jvmMain/kotlin/dev/fritz2/lenses/LensesProcessorProvider.kt
  lenses-annotation-processor/src/jvmMain/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider
  lenses-annotation-processor/src/jvmMain/resources/META-INF/services/javax.annotation.processing.Processor
  lenses-annotation-processor/src/jvmTest/kotlin/dev/fritz2/lenses/LensesAnnotationProcessorTests.kt
  lenses-annotation-processor/src/jvmTest/kotlin/dev/fritz2/lenses/LensesProcessorTests.kt
  settings.gradle.kts
Labels: enhancement, api breaking

#565 Polish Shortcut API
  README.md
  components/src/jsMain/kotlin/dev/fritz2/components/popover.kt
  components/src/jsMain/kotlin/dev/fritz2/components/slider/component.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/html/events.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/listener.kt
  core/src/jsTest/kotlin/dev/fritz2/dom/html/events.kt
  core/src/jsTest/kotlin/dev/fritz2/dom/listener.kt
Labels: api improvement, api breaking

#566 Improve Badges
  README.md
Labels: documentation

#568 `Authentication.complete()` function sets the principal also without running auth-process
  core/src/jsMain/kotlin/dev/fritz2/remote/auth.kt
Labels: bug

#569 Fix .gitignore for api folder
  .gitignore
  api/index.md
Labels: enhancement

#579 Fixed exception handling in Handlers
  core/src/jsMain/kotlin/dev/fritz2/binding/store.kt
  core/src/jsMain/kotlin/dev/fritz2/binding/substores.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/html/job.kt
  core/src/jsMain/kotlin/dev/fritz2/routing/routing.kt
  core/src/jsTest/kotlin/dev/fritz2/binding/handlers.kt
  core/src/jsTest/kotlin/dev/fritz2/binding/mount.kt
  core/src/jsTest/kotlin/dev/fritz2/binding/store.kt
  core/src/jsTest/kotlin/dev/fritz2/remote/websocket.kt
  core/src/jsTest/kotlin/dev/fritz2/repositories/localstorage/localStorage.kt
  core/src/jsTest/kotlin/dev/fritz2/repositories/rest/rest.kt
Labels: bug
