Repository jwstegemann/fritz2, pull requests merged in 2022-02, with the labels that each got.

#571 `Authentication.getPrincipal()` function returns the principal also when pre-setting it before any process is started
  core/src/jsMain/kotlin/dev/fritz2/remote/auth.kt
  core/src/jsMain/kotlin/dev/fritz2/remote/http.kt
  core/src/jsTest/kotlin/dev/fritz2/remote/auth.kt
  gradle.properties
  test-server/src/main/kotlin/dev/fritz2/Server.kt
Labels: bug

#570 New Validation approach
  core/src/commonMain/kotlin/dev/fritz2/identification/inspector.kt
  core/src/commonMain/kotlin/dev/fritz2/validation/validation.kt
  core/src/commonTest/kotlin/dev/fritz2/validation/test/validation.kt
  core/src/commonTest/kotlin/dev/fritz2/validation/validation.kt
  core/src/jsMain/kotlin/dev/fritz2/binding/handlers.kt
  core/src/jsMain/kotlin/dev/fritz2/binding/store.kt
  core/src/jsMain/kotlin/dev/fritz2/binding/substores.kt
  core/src/jsMain/kotlin/dev/fritz2/validation/validation.kt
  core/src/jsTest/kotlin/dev/fritz2/validation/validation.kt
  core/src/jvmMain/kotlin/dev/fritz2/validation/validation.kt
  headless/src/commonMain/kotlin/dev/fritz2/headless/validation/validation.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/hooks/databinding.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/validation/validation.kt
Labels: enhancement, api improvement, api breaking

#580 Transitions controlled by Flow
  core/src/jsMain/kotlin/dev/fritz2/dom/dom.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/html/transitions.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/tag.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/listbox.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/menu.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/popover.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/popperPanel.kt
Labels: enhancement

#581 Upgrading dokka to current version 1.6.10
  .gitignore
  api/index.md
  build.gradle.kts
Labels: documentation

#582 Change Structure of basic Types
  core/src/jsMain/kotlin/dev/fritz2/dom/comment.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/html/attributes.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/html/elements.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/html/events.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/html/htmltag.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/html/rendercontext.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/html/svgtag.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/html/transitions.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/listener.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/mount.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/tag.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/text.kt
  core/src/jsMain/kotlin/dev/fritz2/webcomponents/webcomponents.kt
  core/src/jsTest/kotlin/dev/fritz2/binding/events.kt
  core/src/jsTest/kotlin/dev/fritz2/dom/html/events.kt
  core/src/jsTest/kotlin/dev/fritz2/dom/listener.kt
  core/src/jsTest/kotlin/dev/fritz2/test/utils.kt
  core/src/jsTest/kotlin/dev/fritz2/webcomponents/webcomponent.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/app.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/checkboxGroup.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/disclosure.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/listbox.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/menu.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/modal.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/popover.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/radioGroup.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/switch.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/tabs.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/checkboxGroup.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/disclosure.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/listbox.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/menu.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/modal.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/popOver.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/radioGroup.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/switch.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/tabGroup.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/textfields.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/tooltip.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/openclose.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/popperPanel.kt
  www/src/pages/headless/listbox.md
Labels: api breaking

#585 Rework fritz2 core event concept
  core/src/jsMain/kotlin/dev/fritz2/dom/events.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/html/job.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/html/shortcuts.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/listener.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/tag.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/window.kt
  core/src/jsMain/kotlin/dev/fritz2/routing/routing.kt
  core/src/jsTest/kotlin/dev/fritz2/binding/store.kt
  core/src/jsTest/kotlin/dev/fritz2/dom/events.kt
  core/src/jsTest/kotlin/dev/fritz2/dom/window.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/modal.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/checkboxGroup.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/listbox.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/menu.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/radioGroup.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/switch.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/tabGroup.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/tooltip.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/OpenClose.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/PopUpPanel.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/focus.kt
Labels: api improvement, api breaking

#592 Added `toString()` method to `Scope.Key` class
  core/src/jsMain/kotlin/dev/fritz2/dom/html/scope.kt
Labels: enhancement

#591 fritz2 API cleanup
  core/src/jsMain/kotlin/dev/fritz2/binding/store.kt
  core/src/jsMain/kotlin/dev/fritz2/binding/substores.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/html/job.kt
  core/src/jsMain/kotlin/dev/fritz2/validation/validation.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/menu.kt
  www/src/pages/blog.njk
  www/src/pages/recipes/Recipes.md
Labels: api improvement, api breaking

#594 Improve error handling when dealing with lenses
  core/src/commonMain/kotlin/dev/fritz2/lenses/lens.kt
  core/src/jsMain/kotlin/dev/fritz2/binding/mount.kt
  core/src/jsMain/kotlin/dev/fritz2/dom/html/job.kt
  core/src/jsMain/kotlin/dev/fritz2/routing/routing.kt
  core/src/jsTest/kotlin/dev/fritz2/binding/handlers.kt
  core/src/jsTest/kotlin/dev/fritz2/binding/store.kt
  core/src/jsTest/kotlin/dev/fritz2/remote/websocket.kt
  core/src/jsTest/kotlin/dev/fritz2/repositories/localstorage/localStorage.kt
  core/src/jsTest/kotlin/dev/fritz2/repositories/rest/rest.kt
  core/src/jsTest/kotlin/dev/fritz2/tracking/tracking.kt
Labels: enhancement, api improvement

#598 Adjust README.md
  README.md
Labels: documentation

#599 Complete missing API Documentation for headless module
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/checkboxGroup.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/OpenClose.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/PopUpPanel.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/aria.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/attributes.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/export.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/focus.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/foundation.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/hooks.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/initialize.kt
Labels: docs

#600 Fixes and improvements for new webpage
  .github/workflows/libs.yml
  www/.eleventy.js
  www/src/index.njk
Labels: documentation

#602 Add version number from Gradle to webpages
  .github/workflows/www.yml
  build.gradle.kts
  www/src/_data/fritz2.json
  www/src/_includes/layouts/pageWithNav.njk
  www/src/scripts/main.js
Labels: documentation

#601 Fix open and close behaviour for `OpenClose` based components
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/disclosure.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/modal.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/popOver.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/disclosure.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/listbox.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/menu.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/popOver.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/tooltip.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/OpenClose.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/PopUpPanel.kt
  www/src/pages/headless/headless.md
  www/src/pages/headless/popOver.md
Labels: bug, api improvement

#606 Translate Headless Docs to English
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/disclosure.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/listbox.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/menu.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/modal.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/popOver.kt
  www/src/pages/headless/checkboxGroup.md
  www/src/pages/headless/disclosure.md
  www/src/pages/headless/headless.md
  www/src/pages/headless/inputField.md
  www/src/pages/headless/listbox.md
  www/src/pages/headless/menu.md
  www/src/pages/headless/modal.md
  www/src/pages/headless/popOver.md
  www/src/pages/headless/radioGroup.md
  www/src/pages/headless/switch.md
  www/src/pages/headless/tabGroup.md
  www/src/pages/headless/textArea.md
Labels: documentation, docs

#610 Remove not needed `initDocument` function from tests
  core/src/jsTest/kotlin/dev/fritz2/core/attributes.kt
  core/src/jsTest/kotlin/dev/fritz2/core/dom.kt
  core/src/jsTest/kotlin/dev/fritz2/core/events.kt
  core/src/jsTest/kotlin/dev/fritz2/core/handlers.kt
  core/src/jsTest/kotlin/dev/fritz2/core/mount.kt
  core/src/jsTest/kotlin/dev/fritz2/core/patch.kt
  core/src/jsTest/kotlin/dev/fritz2/core/rendercontext.kt
  core/src/jsTest/kotlin/dev/fritz2/core/scope.kt
  core/src/jsTest/kotlin/dev/fritz2/core/store.kt
  core/src/jsTest/kotlin/dev/fritz2/core/substores.kt
  core/src/jsTest/kotlin/dev/fritz2/core/tags.kt
  core/src/jsTest/kotlin/dev/fritz2/history/history.kt
  core/src/jsTest/kotlin/dev/fritz2/remote/auth.kt
  core/src/jsTest/kotlin/dev/fritz2/remote/websocket.kt
  core/src/jsTest/kotlin/dev/fritz2/repository/localstorage/localStorage.kt
  core/src/jsTest/kotlin/dev/fritz2/repository/rest/rest.kt
  core/src/jsTest/kotlin/dev/fritz2/routing/routing.kt
  core/src/jsTest/kotlin/dev/fritz2/test.kt
  core/src/jsTest/kotlin/dev/fritz2/tracking/tracking.kt
  core/src/jsTest/kotlin/dev/fritz2/validation/validation.kt
  core/src/jsTest/kotlin/dev/fritz2/webcomponents/webcomponent.kt
Labels: enhancement

#611 Use `asString()` method instead
  core/src/jsMain/kotlin/dev/fritz2/core/tags.kt
  core/src/jsTest/kotlin/dev/fritz2/history/history.kt
Labels: enhancement

#612 Resolve todos & fixmes
  core/src/jsMain/kotlin/dev/fritz2/core/mount.kt
  core/src/jsMain/kotlin/dev/fritz2/core/rendercontext.kt
  core/src/jsMain/kotlin/dev/fritz2/core/substores.kt
  core/src/jsTest/kotlin/dev/fritz2/core/events.kt
Labels: enhancement

#613 Small improvement on `PopUpPanel`
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/PopUpPanel.kt
Labels: enhancement

#605 Added tests to headless project
  build.gradle.kts
  core/src/jsMain/kotlin/dev/fritz2/validation/validation.kt
  headless-demo/build.gradle.kts
  headless/build.gradle.kts
  headless/src/commonMain/kotlin/dev/fritz2/headless/validation/validation.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/checkboxGroup.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/listbox.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/menu.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/radioGroup.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/switch.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/tabGroup.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/textfields.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/tooltip.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/DatabindingProperty.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/OpenClose.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/Property.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/ValidationMessages.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/aria.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/export.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/hooks.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/utils/popper/popper.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/utils/scrollintoview/scrollintoview.kt
  headless/src/jsTest/kotlin/dev/fritz2/headless/components/listbox.kt
  headless/src/jsTest/kotlin/dev/fritz2/headless/components/switch.kt
  headless/src/jsTest/kotlin/dev/fritz2/headless/foundation/DataBindingProperty.kt
  headless/src/jsTest/kotlin/dev/fritz2/headless/foundation/OpenClose.kt
  headless/src/jsTest/kotlin/dev/fritz2/headless/foundation/Property.kt
  headless/src/jsTest/kotlin/dev/fritz2/headless/foundation/aria.kt
  headless/src/jsTest/kotlin/dev/fritz2/headless/foundation/attributes.kt
  headless/src/jsTest/kotlin/dev/fritz2/headless/foundation/export.kt
  headless/src/jsTest/kotlin/dev/fritz2/headless/foundation/foundation.kt
  headless/src/jsTest/kotlin/dev/fritz2/headless/foundation/hooks.kt
  headless/src/jsTest/kotlin/dev/fritz2/headless/model/TestModel.kt
  headless/src/jsTest/kotlin/dev/fritz2/headless/test.kt
  lenses-annotation-processor/build.gradle.kts
Labels: api improvement
