Repository jwstegemann/fritz2, pull requests merged in 2022-03, with the labels that each got.

#614 Update Documentation
  core/src/jsMain/kotlin/dev/fritz2/core/events.kt
  www/src/img/components_basics_1.png
  www/src/img/components_basics_2.png
  www/src/img/components_gettinginteractive_1.png
  www/src/img/components_showcase_1.png
  www/src/pages/docs/100_Web Components.md
  www/src/pages/docs/10_Documentation.md
  www/src/pages/docs/20_Getting Started.md
  www/src/pages/docs/30_Render HTML.md
  www/src/pages/docs/40_State Management.md
  www/src/pages/docs/50_Validation.md
  www/src/pages/docs/60_Routing.md
  www/src/pages/docs/70_Http.md
  www/src/pages/docs/80_Websockets.md
  www/src/pages/docs/90_Repositories.md
  www/src/pages/docs/Attributes and CSS.md
  www/src/pages/docs/Authentication.md
  www/src/pages/docs/Connecting Stores.md
  www/src/pages/docs/Flows.md
  www/src/pages/docs/Format.md
  www/src/pages/docs/Getting Started.md
  www/src/pages/docs/History.md
  www/src/pages/docs/Lenses.md
  www/src/pages/docs/Lists in a Model.md
  www/src/pages/docs/Mount-Point.md
  www/src/pages/docs/Nested Structures.md
  www/src/pages/docs/Project Setup.md
  www/src/pages/docs/Reusable Components.md
  www/src/pages/docs/State Management.md
  www/src/pages/docs/Stores.md
  www/src/pages/docs/ToDos.md
  www/src/pages/docs/Tracking.md
  www/src/pages/docs/Validation.md
Labels: documentation

#616 Add blog post about paradigm changes of components of fritz2
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/foundation.kt
  www/src/_includes/components/postslist.njk
  www/src/_includes/layouts/post.njk
  www/src/blog/posts/my-2nd-post.md
  www/src/blog/posts/my-first-post.md
  www/src/blog/posts/paradigm-shift-for-components.md
  www/src/img/paradigm-shift-for-components.jpg
  www/src/pages/blog.njk
  www/src/pages/headless/headless.md
Labels: docs

#617 Headless DataCollection
  core/src/jsMain/kotlin/dev/fritz2/core/listener.kt
  core/src/jsMain/kotlin/dev/fritz2/core/mount.kt
  core/src/jsMain/kotlin/dev/fritz2/core/myer.kt
  core/src/jsMain/kotlin/dev/fritz2/core/rendercontext.kt
  core/src/jsMain/kotlin/dev/fritz2/core/store.kt
  core/src/jsMain/kotlin/dev/fritz2/core/tags.kt
  core/src/jsTest/kotlin/dev/fritz2/core/myer.kt
  headless-demo/build.gradle.kts
  headless-demo/src/commonMain/kotlin/dev/fritz2/headlessdemo/dataCollectionModel.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/app.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/dataCollection.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/icons.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/dataCollection.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/listbox.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/menu.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/sorting.kt
  www/src/pages/headless/dataCollection.md
Labels: enhancement

#622 Fix invocation of Handlers
  core/src/jsMain/kotlin/dev/fritz2/core/handlers.kt
  core/src/jsMain/kotlin/dev/fritz2/core/job.kt
  core/src/jsTest/kotlin/dev/fritz2/core/handlers.kt
  core/src/jsTest/kotlin/dev/fritz2/test.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/OpenClose.kt
  headless/src/jsTest/kotlin/dev/fritz2/headless/foundation/OpenClose.kt
  headless/src/jsTest/kotlin/dev/fritz2/headless/test.kt
Labels: bug
