Repository jwstegemann/fritz2, pull requests merged in 2022-11, with the labels that each got.

#707 Repair remote auth middleware - prevent endless loop for 403 response
  core/src/jsMain/kotlin/dev/fritz2/remote/auth.kt
Labels: api breaking

#709 Add documentation about unsafe tracking functions
  www/src/pages/docs/30_State Management.md
Labels: documentation

#711 Improve handling of nullable values in Stores
  core/src/commonMain/kotlin/dev/fritz2/core/lens.kt
  core/src/commonTest/kotlin/dev/fritz2/core/lens.kt
  core/src/jsMain/kotlin/dev/fritz2/core/store.kt
  core/src/jsMain/kotlin/dev/fritz2/core/substores.kt
  core/src/jsTest/kotlin/dev/fritz2/core/nullable.kt.kt
  core/src/jsTest/kotlin/dev/fritz2/core/substores.kt
  www/src/pages/docs/30_State Management.md
Labels: enhancement

#701 Add headless `Toast` component
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/app.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/toast.kt
  headless-demo/tests/toast.spec.ts
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/toast.kt
  www/src/pages/headless/toast.md
Labels: headless

#727 Resolve bug with alsoExpression on Hook with Flow
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/aria.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/attributes.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/hooks.kt
  headless/src/jsTest/kotlin/dev/fritz2/headless/foundation/hooks.kt
Labels: bug, api breaking
