Repository jwstegemann/fritz2, pull requests merged in 2023-01, with the labels that each got.

#732 Rework Documentation
  core/src/jsMain/kotlin/dev/fritz2/history/history.kt
  snippets/src/jsMain/kotlin/dev/fritz2/examplesdemo/app.kt
  snippets/src/jsMain/kotlin/dev/fritz2/examplesdemo/fundamentals.kt
  www/.eleventy.js
  www/markdown-it-iframe.js
  www/package-lock.json
  www/package.json
  www/src/_includes/components/toc.njk
  www/src/blog/posts/paradigm-shift-for-components.md
  www/src/pages/docs/00_Documentation.md
  www/src/pages/docs/100_Web Components.md
  www/src/pages/docs/10_Getting Started.md
  www/src/pages/docs/20_Fundamentals.md
  www/src/pages/docs/20_Render HTML.md
  www/src/pages/docs/210_Gliederung.md.bak
  www/src/pages/docs/30_Render HTML.md
  www/src/pages/docs/30_State Management.md
  www/src/pages/docs/40_StoreCreation.md
  www/src/pages/docs/50_StoreMapping.md
  www/src/pages/docs/60_Routing.md
  www/src/pages/docs/60_Validation.md
  www/src/pages/docs/80_Http.md
  www/src/pages/docs/80_Repositories.md
  www/src/pages/docs/90_Websockets.md
  www/src/pages/headless/headlessComponents.md
  www/src/pages/headless/modal.md
Labels: documentation

#735 Optimize Efficiency of render and renderText
  core/src/jsMain/kotlin/dev/fritz2/core/mount.kt
  core/src/jsTest/kotlin/dev/fritz2/core/rendercontext.kt
  core/src/jsTest/kotlin/dev/fritz2/core/tags.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/checkboxGroup.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/listbox.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/radioGroup.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/switch.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/textfields.kt
  www/src/pages/recipes/Recipes.md.bak
Labels: enhancement

#739 Fixes focus-trap functions
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/app.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/checkboxGroup.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/dataCollection.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/disclosure.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/icons.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/inputField.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/listbox.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/menu.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/modal.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/popOver.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/radioGroup.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/switch.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/tabGroup.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/textArea.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/toast.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/tooltip.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/foundation/focus.kt
  headless-demo/tests/components/checkbox.spec.ts
  headless-demo/tests/components/datacollection.datatable.spec.ts
  headless-demo/tests/components/datacollection.gridlist.spec.ts
  headless-demo/tests/components/disclosure.spec.ts
  headless-demo/tests/components/inputfield.spec.ts
  headless-demo/tests/components/listbox.spec.ts
  headless-demo/tests/components/menu.spec.ts
  headless-demo/tests/components/modal.spec.ts
  headless-demo/tests/components/popover.spec.ts
  headless-demo/tests/components/radio.spec.ts
  headless-demo/tests/components/switch.spec.ts
  headless-demo/tests/components/tabgroup.spec.ts
  headless-demo/tests/components/textarea.spec.ts
  headless-demo/tests/components/toast.spec.ts
  headless-demo/tests/components/tooltip.spec.ts
  headless-demo/tests/foundation/focus.spec.ts
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/listbox.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/menu.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/modal.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/focus.kt
Labels: bug, api breaking

#740 Simplify Tracker to use Boolean as state
  core/src/jsMain/kotlin/dev/fritz2/tracking/tracking.kt
  core/src/jsTest/kotlin/dev/fritz2/tracking/tracking.kt
  examples/masterdetail/src/jsMain/kotlin/dev/fritz2/examples/masterdetail/masterdetail.kt
Labels: api breaking

#742 Improve gradle-settings
  gradle.properties
Labels: enhancement

#741 Fix bug stopping handler on re-rendering
  core/src/jsMain/kotlin/dev/fritz2/core/handlers.kt
  core/src/jsMain/kotlin/dev/fritz2/core/mount.kt
  core/src/jsMain/kotlin/dev/fritz2/core/store.kt
  core/src/jsTest/kotlin/dev/fritz2/core/handlers.kt
  core/src/jsTest/kotlin/dev/fritz2/core/job.kt
  core/src/jsTest/kotlin/dev/fritz2/core/store.kt
  headless/src/jsTest/kotlin/dev/fritz2/headless/components/listbox.kt
Labels: bug
