Repository jwstegemann/fritz2, pull requests merged in 2023-08, with the labels that each got.

#777 Use variable `fritz2.version` in 10_Getting Started.md instead of fixed one
  www/package-lock.json
  www/src/pages/docs/10_Getting Started.md
Labels: documentation

#783 Utility functions for `RenderContext`
  core/src/jsMain/kotlin/dev/fritz2/core/rendercontext.kt
Labels: api improvement

#794 Fix and improve some mapping example
  www/src/pages/docs/50_StoreMapping.md
Labels: documentation

#795 fix afterUnmount crashes due to job cancellation
  core/src/jsMain/kotlin/dev/fritz2/core/mount.kt
  core/src/jsTest/kotlin/dev/fritz2/core/mount.kt
Labels: bug
