Repository jwstegemann/fritz2, pull requests merged in 2024-09, with the labels that each got.

#883 Upgrades publishing pipeline `upload-artifact` task to v4
  .github/workflows/libs.yml
Labels: bug

#879 Improve export-API so it cannot throw anymore
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/export.kt
  headless/src/jsTest/kotlin/dev/fritz2/headless/foundation/export.kt
Labels: api improvement, api breaking

#876 Introduce automatic Generation of Delegating Lenses: Improves Validation Support for Sealed Class Hierarchies
  core/src/commonMain/kotlin/dev/fritz2/core/lens.kt
  core/src/commonTest/kotlin/dev/fritz2/core/inspector.kt
  core/src/commonTest/kotlin/dev/fritz2/core/lens.kt
  lenses-annotation-processor/src/jvmMain/kotlin/dev/fritz2/lens/LenseablePropertiesDeterminer.kt
  lenses-annotation-processor/src/jvmMain/kotlin/dev/fritz2/lens/LensesProcessor.kt
  lenses-annotation-processor/src/jvmMain/kotlin/dev/fritz2/lens/LowerCamelCased.kt
  lenses-annotation-processor/src/jvmMain/kotlin/dev/fritz2/lens/Message.kt
  lenses-annotation-processor/src/jvmMain/kotlin/dev/fritz2/lens/RequirementChecks.kt
  lenses-annotation-processor/src/jvmMain/kotlin/dev/fritz2/lens/TypeVariant.kt
  lenses-annotation-processor/src/jvmTest/kotlin/dev/fritz2/lens/LensesProcessorTests.kt
Labels: enhancement

#880 Adds a headless `combobox` component
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/app.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/combobox.kt
  headless-demo/tests/components/combobox.spec.ts
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/combobox.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/PopUpPanel.kt
  www/src/pages/headless/combobox.md
Labels: enhancement

#886 Add new `@NoLens` annotation
  core/api/core.api
  core/src/commonMain/kotlin/dev/fritz2/core/lens.kt
  lenses-annotation-processor/src/jvmMain/kotlin/dev/fritz2/lens/LenseablePropertiesDeterminer.kt
  lenses-annotation-processor/src/jvmTest/kotlin/dev/fritz2/lens/LensesProcessorTests.kt
Labels: enhancement

#887 Add missing events
  core/src/jsMain/kotlin/dev/fritz2/core/events.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/combobox.kt
Labels: enhancement

#889 Improves handling of null values in the headless combobox
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/combobox.kt
  headless-demo/tests/components/combobox.spec.ts
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/combobox.kt
  www/src/pages/headless/combobox.md
Labels: enhancement, headless

#888 Improve PopUpPanel Performance
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/PopUpPanel.kt
Labels: headless

#892 Updates GitHub profile links in the website footer
  www/src/index.njk
Labels: website

#894 Enables empty sealed types to generate up-casting lenses
  lenses-annotation-processor/src/jvmMain/kotlin/dev/fritz2/lens/LenseablePropertiesDeterminer.kt
  lenses-annotation-processor/src/jvmMain/kotlin/dev/fritz2/lens/LensesProcessor.kt
  lenses-annotation-processor/src/jvmMain/kotlin/dev/fritz2/lens/RequirementChecks.kt
  lenses-annotation-processor/src/jvmTest/kotlin/dev/fritz2/lens/LensesProcessorTests.kt
Labels: bug

#898 Add documentation for sealed type-hierarchies
  www/package-lock.json
  www/package.json
  www/src/img/sealed-hierarchy-example-app.png
  www/src/pages/docs/30_Render HTML.md
  www/src/pages/docs/50_StoreMapping.md
  www/src/pages/docs/70_Validation.md
Labels: documentation

#902 Fixes small styling issue in sealed hierarchy example
  www/src/pages/docs/50_StoreMapping.md
Labels: documentation
