Repository jwstegemann/fritz2, pull requests merged in 2024-11, with the labels that each got.

#913 Combobox: Only accept distinct values via data-binding
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/combobox.kt
Labels: bug, headless

#914 Standardizes the combobox selectionStrategy name to autoSelectMatch
  headless-demo/src/commonMain/kotlin/dev/fritz2/headlessdemo/components/ComboboxDemoConfig.kt
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/combobox.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/combobox.kt
  www/src/pages/headless/combobox.md
Labels: documentation

#917 Fixes minor mistake in Event Handling documentation
  www/src/pages/docs/45_EventHandling.md
Labels: documentation

#918 Updates 11ty to version 3.0.0
  www/package-lock.json
  www/package.json
Labels: dependencies, website

#921 Fix setting an initial value for the ComboBox
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/Combobox.kt
Labels: bug, headless

#923 Update broken references
  examples/todomvc/src/jsMain/resources/index.html
  www/src/blog/posts/paradigm-shift-for-components.md
  www/src/pages/docs/45_EventHandling.md
Labels: documentation
