Repository jwstegemann/fritz2, pull requests merged in 2024-01, with the labels that each got.

#834 do not use flatMapLatest for events
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/dataCollection.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/tabGroup.kt
Labels: headless

#835 Improves PopUpPanel
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/popOver.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/PopUpPanel.kt
  www/src/pages/headless/headlessComponents.md
  www/src/pages/headless/listbox.md
  www/src/pages/headless/menu.md
  www/src/pages/headless/popOver.md
  www/src/pages/headless/tooltip.md
Labels: api improvement, headless

#839 Add documentation for `Store`s `current` property
  www/src/pages/docs/40_StoreCreation.md
Labels: documentation

#840 Review Doc after #839
  www/src/pages/docs/40_StoreCreation.md
Labels: documentation

#833 Henry/fix nested portals
  headless-demo/src/jsMain/kotlin/dev/fritz2/headlessdemo/components/popOver.kt
  headless-demo/tests/components/popover.spec.ts
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/disclosure.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/listbox.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/menu.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/popOver.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/OpenClose.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/PopUpPanel.kt
  headless/src/jsTest/kotlin/dev/fritz2/headless/foundation/OpenClose.kt
Labels: bug, headless

#841 Refresh Versions for upcoming RC13 Release
  headless-demo/tests/components/datacollection.datatable.spec.ts
  headless-demo/tests/components/datacollection.gridlist.spec.ts
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/utils/scrollintoview/scrollintoview.kt
  kotlin-js-store/yarn.lock
  versions.properties
Labels: dependencies

#842 Fix Selection Behaviour of ListBox
  headless-demo/tests/components/listbox.spec.ts
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/listbox.kt
Labels: bug, headless

#845 Update Gradle to v8.5
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#847 Fix implicit dependency error in Gradle for publishing
  core/build.gradle.kts
  headless/build.gradle.kts
  lenses-annotation-processor/build.gradle.kts
  publishing.gradle.kts
  serialization/build.gradle.kts
Labels: dependencies

#848 Use Kotlin default hierarchy template
  core/build.gradle.kts
  examples/gettingstarted/build.gradle.kts
  examples/masterdetail/build.gradle.kts
  examples/nestedmodel/build.gradle.kts
  examples/performance/build.gradle.kts
  examples/remote/build.gradle.kts
  examples/routing/build.gradle.kts
  examples/tictactoe/build.gradle.kts
  examples/todomvc/build.gradle.kts
  examples/validation/build.gradle.kts
  examples/webcomponent/build.gradle.kts
  headless-demo/build.gradle.kts
  headless/build.gradle.kts
  lenses-annotation-processor/build.gradle.kts
  serialization/build.gradle.kts
  snippets/build.gradle.kts
  www/src/pages/docs/10_Getting Started.md
  www/src/pages/headless/headlessComponents.md
Labels: dependencies

#849 Fix ksp configuration in projects
  examples/masterdetail/build.gradle.kts
  examples/nestedmodel/build.gradle.kts
  examples/tictactoe/build.gradle.kts
  examples/todomvc/build.gradle.kts
  examples/validation/build.gradle.kts
  headless-demo/build.gradle.kts
  www/src/pages/docs/10_Getting Started.md
Labels: dependencies

#851 Fix nested listbox selection behavior
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/listbox.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/OpenClose.kt
Labels: headless
