Repository jwstegemann/fritz2, pull requests merged in 2025-01, with the labels that each got.

#930 Updates Playwright to version 1.49.1
  headless-demo/package-lock.json
  headless-demo/package.json
Labels: maintenance

#929 Suppresses unused warning for floating-ui type definitions
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/utils/floatingui/core/Types.kt
  headless/src/jsMain/kotlin/dev/fritz2/headless/foundation/utils/floatingui/utils/Types.kt
Labels: code-cleanup

#928 Add `mapNullable` function to `Store`s and `Inspector`s
  core/api/core.api
  core/src/commonMain/kotlin/dev/fritz2/core/Inspector.kt
  core/src/commonMain/kotlin/dev/fritz2/core/Lens.kt
  core/src/commonTest/kotlin/dev/fritz2/core/Lens.kt
  core/src/jsMain/kotlin/dev/fritz2/core/SubStores.kt
  www/src/pages/docs/50_StoreMapping.md
Labels: enhancement

#933 Fixes a small potential bug on headless switch component
  headless/src/jsMain/kotlin/dev/fritz2/headless/components/Switch.kt
Labels: bug, headless
